"""
Judge agent — synthesizes optimist and skeptic perspectives into a balanced report.
Used in debate mode pipeline.
"""
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import config

JUDGE_PROMPT = """You are a neutral Judge. You have received two perspectives on
the same research topic — one from an Optimist and one from a Skeptic.

Your job is to synthesize both into a single, balanced, nuanced, publication-quality report.

Rules:
- Extract the strongest evidence from BOTH perspectives
- Do not favor one side over the other — show genuine balance
- Where they agree, emphasize consensus
- Where they disagree, present both sides fairly with evidence
- Write 1000-1300 words in professional Markdown
- Structure:
  # [Topic]: A Balanced Analysis
  > **Executive Summary:** [Balanced 3-sentence overview]
  ## Points of Consensus
  ## The Optimistic Case
  ## The Critical Concerns
  ## Balanced Assessment
  ## Key Takeaways
  ## Sources
---
*Report generated by AI Multi-Agent Research System (Debate Mode)*
"""


def run_judge(optimist_report: str, skeptic_report: str, research_data: str, query: str) -> str:
    """Synthesize optimist and skeptic perspectives into a balanced final report."""
    llm = ChatGroq(
        model=config.GROQ_MODEL,
        temperature=0.3,
        api_key=config.GROQ_API_KEY,
    )
    prompt = ChatPromptTemplate.from_messages([
        ("system", JUDGE_PROMPT),
        ("human", "Topic: {query}\n\n"
                  "Original research data:\n{research_data}\n\n"
                  "OPTIMIST REPORT:\n{optimist}\n\n"
                  "SKEPTIC REPORT:\n{skeptic}\n\n"
                  "Now write your balanced synthesis."),
    ])
    return (prompt | llm | StrOutputParser()).invoke({
        "query": query,
        "research_data": research_data,
        "optimist": optimist_report,
        "skeptic": skeptic_report,
    })
