from typing import AsyncGenerator
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from agents.schemas import WriterOutput
from agents.llm_factory import get_primary_llm, get_fallback_llm, get_llm

SYSTEM_PROMPT = """You are a Professional Technical Writer. You take
structured analysis and produce polished, well-written reports.

INSTRUCTIONS:
1. Write a comprehensive report based on the analysis provided.
2. Use clear, professional language suitable for a general audience.
3. Include an executive summary (3-4 sentences).
4. Create clear main sections with headings.
5. Include relevant statistics and data points in context.
6. All referenced URLs go in the sources list.
7. Keep the report between 800-1500 words.
8. End with 3-5 key takeaways.

Write clearly and factually. Do NOT invent information beyond what's in the analysis.
"""

REVISION_PREFIX = """REVISION REQUIRED — the reviewer flagged issues with the previous draft.
Address these specific revision instructions FIRST, then produce your improved report:

{revision_instructions}

---

"""


def build_writer_chain(language: str = "English"):
    lang_note = _lang_suffix(language)
    system = SYSTEM_PROMPT + lang_note
    prompt = ChatPromptTemplate.from_messages([
        ("system", system),
        ("human", "{revision_block}Original topic: {query}\n\n"
                  "Structured analysis:\n{analysis}\n\n"
                  "Write the full report now."),
    ])
    primary_chain = prompt | get_primary_llm(0.4).with_structured_output(WriterOutput)
    fallback_chain = prompt | get_fallback_llm(0.4).with_structured_output(WriterOutput)
    return primary_chain.with_fallbacks([fallback_chain])


def _lang_suffix(language: str) -> str:
    """Return a language instruction suffix for non-English outputs."""
    if not language or language.lower() in ("english", "en"):
        return ""
    return f"\n\nIMPORTANT: Write the ENTIRE report in {language}. All headings, content, summaries, and takeaways must be in {language}."


def run_writer(analysis: str, query: str, revision_instructions: str = "", language: str = "English") -> WriterOutput:
    """Run the writer chain and return structured WriterOutput."""
    chain = build_writer_chain(language)
    revision_block = ""
    if revision_instructions:
        revision_block = REVISION_PREFIX.format(revision_instructions=revision_instructions)
    return chain.invoke({
        "analysis": analysis,
        "query": query,
        "revision_block": revision_block,
    })


async def astream_writer(
    analysis: str,
    query: str,
    revision_instructions: str = "",
    language: str = "English",
) -> AsyncGenerator[str, None]:
    """
    Async generator that streams writer output token-by-token.
    Yields raw Markdown chunks — accumulate them for the full report.
    Uses a plain StrOutputParser chain (not structured output) to enable streaming.
    """
    lang_note = _lang_suffix(language)
    stream_system = SYSTEM_PROMPT + lang_note + "\n\nWrite in plain Markdown. Start directly with # Title."

    prompt = ChatPromptTemplate.from_messages([
        ("system", stream_system),
        ("human", "{revision_block}Original topic: {query}\n\n"
                  "Structured analysis:\n{analysis}\n\n"
                  "Write the full Markdown report now."),
    ])
    # Use get_llm() which returns primary.with_fallbacks([fallback])
    # StrOutputParser works fine on RunnableWithFallbacks
    chain = prompt | get_llm(0.4, streaming=True) | StrOutputParser()

    revision_block = ""
    if revision_instructions:
        revision_block = REVISION_PREFIX.format(revision_instructions=revision_instructions)

    async for chunk in chain.astream({
        "analysis": analysis,
        "query": query,
        "revision_block": revision_block,
    }):
        yield chunk


def writer_to_markdown(output: WriterOutput) -> str:
    """Convert structured WriterOutput to full Markdown report."""
    lines = [f"# {output.title}"]
    lines.append(f"> **Executive Summary:** {output.executive_summary}\n")

    for section in output.sections:
        lines.append(f"## {section.heading}")
        lines.append(section.content)
        lines.append("")

    lines.append("## Key Takeaways")
    for takeaway in output.key_takeaways:
        lines.append(f"- {takeaway}")
    lines.append("")

    lines.append("## Sources")
    for source in output.sources:
        lines.append(f"- {source}")
    lines.append("")

    lines.append("---")
    lines.append("*Report generated by AI Multi-Agent Research System*")

    return "\n".join(lines)
