from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from agents.schemas import WriterOutput
import config

SYSTEM_PROMPT = """You are a Professional Technical Writer. You take
structured analysis and produce polished, well-written reports.

INSTRUCTIONS:
1. Write a comprehensive report based on the analysis provided.
2. Use clear, professional language suitable for a general audience.
3. Include an executive summary (3-4 sentences).
4. Create clear main sections with headings.
5. Include relevant statistics and data points in context.
6. All referenced URLs go in the sources list.
7. Keep the report between 800-1500 words.
8. End with 3-5 key takeaways.

Write clearly and factually. Do NOT invent information beyond what's in the analysis.
"""

REVISION_PREFIX = """REVISION REQUIRED — the reviewer flagged issues with the previous draft.
Address these specific revision instructions FIRST, then produce your improved report:

{revision_instructions}

---

"""


def build_writer_chain():
    llm = ChatGroq(
        model=config.GROQ_MODEL,
        temperature=0.4,
        api_key=config.GROQ_API_KEY,
    )
    structured_llm = llm.with_structured_output(WriterOutput)

    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT),
        ("human", "{revision_block}Original topic: {query}\n\n"
                  "Structured analysis:\n{analysis}\n\n"
                  "Write the full report now."),
    ])

    return prompt | structured_llm


def run_writer(analysis: str, query: str, revision_instructions: str = "") -> WriterOutput:
    """Run the writer chain and return structured WriterOutput."""
    chain = build_writer_chain()
    revision_block = ""
    if revision_instructions:
        revision_block = REVISION_PREFIX.format(revision_instructions=revision_instructions)
    return chain.invoke({
        "analysis": analysis,
        "query": query,
        "revision_block": revision_block,
    })


def writer_to_markdown(output: WriterOutput) -> str:
    """Convert structured WriterOutput to full Markdown report."""
    lines = [f"# {output.title}"]
    lines.append(f"> **Executive Summary:** {output.executive_summary}\n")

    for section in output.sections:
        lines.append(f"## {section.heading}")
        lines.append(section.content)
        lines.append("")

    lines.append("## Key Takeaways")
    for takeaway in output.key_takeaways:
        lines.append(f"- {takeaway}")
    lines.append("")

    lines.append("## Sources")
    for source in output.sources:
        lines.append(f"- {source}")
    lines.append("")

    lines.append("---")
    lines.append("*Report generated by AI Multi-Agent Research System*")

    return "\n".join(lines)
