from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import config

SYSTEM_PROMPT = """You are a Professional Technical Writer. You take 
structured analysis and produce polished, well-written reports.

INSTRUCTIONS:
1. Write a comprehensive report based on the analysis provided.
2. Use clear, professional language suitable for a general audience.
3. Structure the report with proper Markdown formatting.
4. Include an executive summary at the top (3-4 sentences).
5. Use headings, subheadings, bullet points, and bold text for readability.
6. Include relevant statistics and data points in context.
7. Add a "Sources" section at the end with all referenced URLs.
8. Keep the report between 800-1500 words.
9. End with a "Key Takeaways" section (3-5 bullet points).

OUTPUT FORMAT (Markdown):
# [Report Title]
> **Executive Summary:** [3-4 sentence overview]

## Introduction
[context and scope]

## [Main Section 1]
[content]

## [Main Section 2]
[content]

## [Additional Sections as needed]
[content]

## Key Takeaways
- [takeaway 1]
- [takeaway 2]
- [takeaway 3]

## Sources
- [source list with URLs]

---
*Report generated by AI Multi-Agent Research System*

Write clearly and factually. Do NOT invent information beyond what's in the analysis.
"""


def build_writer_chain():
    llm = ChatGroq(
        model=config.GROQ_MODEL,
        temperature=0.4,
        api_key=config.GROQ_API_KEY,
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT),
        ("human", "Original topic: {query}\n\n"
                  "Structured analysis:\n{analysis}\n\n"
                  "Write the full report now."),
    ])

    return prompt | llm | StrOutputParser()


def run_writer(analysis: str, query: str) -> str:
    chain = build_writer_chain()
    return chain.invoke({"analysis": analysis, "query": query})
